#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export GIT_EDITOR='emacsclient -t'
export EDITOR='emacsclient -t'
export VISUAL='nano'
export PAGER='less'
export ALTERNATE_EDITOR=""

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
    #/usr/local/share/perl/5.18.2/auto/share/dist/Cope # ubuntu systems
    # /usr/local/share/perl/5.22.1/auto/share/dist/Cope
    $HOME/bin
    $HOME/.local/bin
    $HOME/.autojump/bin
    /usr/local/{bin,sbin}
  	/{bin,sbin}
  	/usr/{bin,sbin}
  	/usr/local/{bin,sbin}
  	/usr/{bin,sbin}
  	$path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="$(mktemp -d)"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
